import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body >
          <Header />
          <div className="w-full flex">
            <Sidebar />
            <div className="flex-1">
              {children}

            </div>

          </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
