import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";


import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body >
          <Header />
          <div className="w-full flex">
            <div>
            <Sidebar />
            </div>
            <div className="flex-1 min-h-screen p-4 md:p-6 bg-gray-300">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
